// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk_k0Xaf6kuV25xXfZD19TZgIcbFU34RA',
    appId: '1:4310722241:web:1cd50e1fee72f542e21640',
    messagingSenderId: '4310722241',
    projectId: 'territory-manager-f3eef',
    authDomain: 'territory-manager-f3eef.firebaseapp.com',
    storageBucket: 'territory-manager-f3eef.firebasestorage.app',
    measurementId: 'G-G0EB08EWEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDACwCrGZyDOn06cf-remKgK1pWz3A3WZI',
    appId: '1:4310722241:android:252a711f79c238ade21640',
    messagingSenderId: '4310722241',
    projectId: 'territory-manager-f3eef',
    storageBucket: 'territory-manager-f3eef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDza-VM2szpZ-IKkd6cOkhElIr_0rxMEmg',
    appId: '1:4310722241:ios:2b68d28a85d0eec5e21640',
    messagingSenderId: '4310722241',
    projectId: 'territory-manager-f3eef',
    storageBucket: 'territory-manager-f3eef.firebasestorage.app',
    iosBundleId: 'com.example.territoryManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDza-VM2szpZ-IKkd6cOkhElIr_0rxMEmg',
    appId: '1:4310722241:ios:2b68d28a85d0eec5e21640',
    messagingSenderId: '4310722241',
    projectId: 'territory-manager-f3eef',
    storageBucket: 'territory-manager-f3eef.firebasestorage.app',
    iosBundleId: 'com.example.territoryManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk_k0Xaf6kuV25xXfZD19TZgIcbFU34RA',
    appId: '1:4310722241:web:f7b7e79cfa8b67d7e21640',
    messagingSenderId: '4310722241',
    projectId: 'territory-manager-f3eef',
    authDomain: 'territory-manager-f3eef.firebaseapp.com',
    storageBucket: 'territory-manager-f3eef.firebasestorage.app',
    measurementId: 'G-M4K4N46GK1',
  );
}
